---

  - name: reboot
    command: shutdown -r now "Reboot triggered by Ansible"
    async: 0
    poll: 0
    sudo: yes
    ignore_errors: true
    notify: wait for restart

  - name: wait for restart
    local_action:
      module: wait_for
        host={{ inventory_hostname }}
        port=22
        delay=1
        timeout=300
      sudo: false