---
- hosts: ev3dev.local
  vars:
    ssid: WebRover1
    wpa_passphrase: testtest
  roles:
    - setup
    - ap
    #- portal   # creating a captive portal (untested)
    - python   # install an ev3_py27 virtualenv with python control
    - web      # install lego rovers web server software
    #- ros      # install a ROS.org node (incomplete)