---

  - name: install dnsmasq
    apt: name=dnsmasq

  - name: configure dnsmasq to provide DHCP access (we disable DNS so that it doesn't clash with connman's)
    copy: src=dnsmasq.conf dest=/etc/dnsmasq.d/ap.conf
    notify: restart dnsmasq

#   service: name=dnsmasq enabled=yes
