---

  - name: apt-get git
    apt: name=git
    sudo: yes

  - name: clone the lego rovers website repo
    git: repo=https://github.com/legorovers/legoflask.git
       dest=/home/robot/web

  - name: install website python requirements
    pip: requirements=/home/robot/web/requirements.txt virtualenv=/home/robot/.virtualenvs/ev3_py27
