---

  - name: apt-get update (~15m if not done in the last day)
    apt: update_cache=yes cache_valid_time=86400
    sudo: yes

  - name: upgrade packages to latest (~1h20m)
    command: apt-get upgrade -y
    sudo: yes

  - name: apt-get dist-upgrade
    apt: upgrade=dist
    sudo: yes
    notify: reboot

  - name: trigger reboot (if necessary)
    meta: flush_handlers
