---

  - name: upgrade packages to latest (~1h20m)
    apt: upgrade=full update_cache=yes
    sudo: yes

  - name: apt-get dist-upgrade
    apt: upgrade=dist
    sudo: yes
    notify: reboot

  - name: trigger reboot (if necessary)
    meta: flush_handlers
